import PDFDocument from 'pdfkit';

export default function generatePDFReport(testState, metrics, stream) {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });

    doc.pipe(stream);

    // --- Header ---
    doc.fillColor("#2196F3")
       .fontSize(26)
       .text("LOADVIZ PERFORMANCE REPORT", { align: "center", bold: true });
    
    doc.moveDown(0.5);
    doc.strokeColor("#E0E0E0")
       .lineWidth(1)
       .moveTo(50, doc.y)
       .lineTo(545, doc.y)
       .stroke();
    
    doc.moveDown(1);

    // --- Metadata ---
    doc.fillColor("#444444").fontSize(9);
    const metaY = doc.y;
    doc.text(`Target URL: ${testState.config.url}`, 50, metaY);
    doc.text(`Method: ${testState.config.method.toUpperCase()}`, 50, metaY + 12);
    doc.text(`Concurrency: ${testState.config.concurrency}`, 50, metaY + 24);
    
    doc.text(`Session ID: ${testState.id}`, 320, metaY);
    doc.text(`Timestamp: ${new Date().toLocaleString()}`, 320, metaY + 12);
    doc.text(`Status: ${testState.status.toUpperCase()}`, 320, metaY + 24);

    doc.moveDown(4);

    // --- Summary Metrics Grid ---
    drawSectionTitle(doc, "Summary Metrics");
    const startX = 50;
    const startY = doc.y;
    const colWidth = 165;
    const rowHeight = 50;

    const drawStat = (label, value, x, y, color) => {
        doc.rect(x, y, colWidth, rowHeight).fillAndStroke("#F8F9FA", "#E0E0E0");
        doc.fillColor("#666666").fontSize(8).text(label.toUpperCase(), x + 10, y + 10);
        doc.fillColor(color).fontSize(16).text(value, x + 10, y + 22, { bold: true });
    };

    drawStat("Success Rate", `${metrics.successRate.toFixed(2)}%`, startX, startY, "#2E7D32");
    drawStat("Avg Latency", `${metrics.avgLatency.toFixed(2)}ms`, startX + colWidth + 2, startY, "#F9A825");
    drawStat("P95 Latency", `${metrics.p95Latency.toFixed(2)}ms`, startX + (colWidth + 2) * 2, startY, "#D84315");

    doc.moveDown(5);
    const row2Y = doc.y;
    drawStat("Throughput", `${metrics.throughput.toFixed(2)} RPS`, startX, row2Y, "#1565C0");
    drawStat("Requests", `${metrics.completed} / ${metrics.totalRequests}`, startX + colWidth + 2, row2Y, "#000000");
    drawStat("Errors", `${metrics.errors}`, startX + (colWidth + 2) * 2, row2Y, "#C62828");

    doc.moveDown(5);

    // --- Charts Section ---
    
    // Line Chart: Needs about 160 units of space.
    checkPageBreak(doc, 160);
    drawSectionTitle(doc, "Performance Trends Over Time");
    drawLineChart(doc, testState.history);
    
    doc.moveDown(1.5);

    // Pie Chart: Needs about 150 units.
    checkPageBreak(doc, 150);
    drawSectionTitle(doc, "Response Distribution Breakdown");
    drawPieChart(doc, metrics.errorStats);

    doc.moveDown(1.5);

    // Latency Histogram
    checkPageBreak(doc, 150);
    drawSectionTitle(doc, "Latency Distribution (ms)");
    drawHistogram(doc, metrics.buckets, metrics.counts);

    // --- Footer ---
    doc.fontSize(8).fillColor("#AAAAAA")
       .text("Automatically generated by LOADVIZ Engine. All performance data is capture-accurate.", 50, doc.page.height - 40, { align: "center" });

    doc.end();
}

function checkPageBreak(doc, heightNeeded) {
    if (doc.y + heightNeeded > doc.page.height - 50) {
        doc.addPage();
    }
}

function drawSectionTitle(doc, title) {
    doc.fillColor("#333333").fontSize(11).text(title, { bold: true });
    doc.moveDown(0.3);
}

function drawLineChart(doc, history) {
    const chartWidth = 500, chartHeight = 110, x = 50, y = doc.y;
    doc.rect(x, y, chartWidth, chartHeight).fill("#FDFDFD").stroke("#EEEEEE");

    if (!history || history.length < 2) {
        doc.fillColor("#999999").fontSize(10).text("Insufficient trend data", x + 190, y + 45);
        doc.y = y + chartHeight + 5;
        return;
    }

    const maxRPS = Math.max(...history.map(h => h.throughput), 1);
    const plotLine = (key, color, max = 100) => {
        doc.strokeColor(color).lineWidth(1.2).opacity(0.8);
        doc.moveTo(x, y + chartHeight - (history[0][key] / max) * chartHeight);
        history.forEach((p, i) => doc.lineTo(x + (i / (history.length - 1)) * chartWidth, y + chartHeight - (p[key] / max) * chartHeight));
        doc.stroke();
    };

    doc.opacity(1).fontSize(7);
    doc.fillColor("#1565C0").text("● Throughput", x + 10, y + 10);
    doc.fillColor("#2E7D32").text("● Success %", x + 80, y + 10);
    doc.fillColor("#C62828").text("● Error %", x + 150, y + 10);

    plotLine('throughput', "#1565C0", maxRPS);
    plotLine('successRate', "#2E7D32", 100);
    plotLine('errorRate', "#C62828", 100);
    doc.y = y + chartHeight + 5;
}

function drawPieChart(doc, errorStats) {
    const x = 50, y = doc.y, radius = 50, centerX = x + radius, centerY = y + radius;
    const data = [
        { label: "Successful (2xx)", count: errorStats.success2xx, color: "#2E7D32" },
        { label: "Redirects (3xx)", count: errorStats.redirect3xx, color: "#EF6C00" },
        { label: "Client Failures (4xx)", count: errorStats.client4xx, color: "#F9A825" },
        { label: "Server Failures (5xx)", count: errorStats.server5xx, color: "#C62828" },
        { label: "Network Errors", count: errorStats.networkErrors, color: "#424242" }
    ];

    const total = data.reduce((acc, d) => acc + d.count, 0);
    if (total === 0) {
        doc.fillColor("#999999").fontSize(10).text("No response data", x + 5, y + 5);
        doc.y = y + 15;
        return;
    }

    let currentAngle = -90; // Start from top
    data.forEach((d, i) => {
        if (d.count === 0) return;
        const sliceAngle = (d.count / total) * 360;
        const startAngle = currentAngle;
        const endAngle = currentAngle + sliceAngle;

        // Draw sector
        doc.fillColor(d.color).opacity(0.8);
        doc.moveTo(centerX, centerY).arc(centerX, centerY, radius, (startAngle * Math.PI) / 180, (endAngle * Math.PI) / 180).lineTo(centerX, centerY).fill();
        
        // Legend text
        const legendX = centerX + radius + 30;
        const legendY = y + 10 + i * 18;
        doc.rect(legendX, legendY, 10, 10).fill(d.color);
        doc.opacity(1).fillColor("#333333").fontSize(9).text(`${d.label}: ${d.count} (${((d.count / total) * 100).toFixed(1)}%)`, legendX + 15, legendY + 1);

        currentAngle = endAngle;
    });

    doc.y = y + (radius * 2) + 10;
}

function drawHistogram(doc, buckets, counts) {
    const chartWidth = 500, chartHeight = 100, x = 50, y = doc.y;
    doc.rect(x, y, chartWidth, chartHeight).fill("#FDFDFD").stroke("#EEEEEE");

    if (!counts || counts.every(c => c === 0)) {
        doc.fillColor("#999999").fontSize(10).text("No latency data", x + 190, y + 45);
        doc.y = y + chartHeight + 5;
        return;
    }

    const maxCount = Math.max(...counts, 1);
    const barWidth = (chartWidth - 40) / counts.length;

    counts.forEach((count, i) => {
        const h = (count / maxCount) * (chartHeight - 30);
        doc.fillColor("#2196F3").opacity(0.8).rect(x + 20 + i * barWidth, y + chartHeight - h - 20, barWidth - 2, h).fill();
        doc.opacity(1).fillColor("#666666").fontSize(6).text(buckets[i], x + 20 + i * barWidth, y + chartHeight - 12);
    });

    doc.y = y + chartHeight + 5;
}
